AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ftrack-change-status-lamda

  Sample SAM Template for ftrack-change-status-lamda


Parameters:
  FtrackServer:
    Type: String
    Default: https://<MyCompanyName>.ftrackapp.com/
  FtrackApiKey:
    Type: String
    Default: <User or global API Key>
  FtrackApiUser:
    Type: String
    Default: <Your ftrack Login User>

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128


Resources:
  StatusChangeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: status_change/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        StatusChange:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /status_change
            Method: post

      Environment:
        Variables:
          FTRACK_SERVER: !Ref FtrackServer
          FTRACK_API_KEY: !Ref FtrackApiKey
          FTRACK_API_USER: !Ref FtrackApiUser
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 3

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StatusChangeApi:
    Description: "API Gateway endpoint URL for Prod stage for Status Change function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/status_change/"
  StatusChangeFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt StatusChangeFunction.Arn
  StatusChangeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt StatusChangeFunctionRole.Arn
